services:
  # Backend
  backend:
    build: .
    container_name: edu-connect-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      APP_NAME: EduConnect
      APP_VERSION: 1.0.0
      APP_DESCRIPTION: "This is a social media for students"
      DATABASE_URL: "mysql://root:root@mysql:3306/edu_connect"
      PASSWORD_HASHING_ROUNDS: "10"
      ACCESS_TOKEN_SECRET_KEY: secret_key
      REFRESH_TOKEN_SECRET_KEY: refresh_secret_key
      IS_HTTP_COOKIE: "true"
      SWAGGER_ENDPOINT: "/api-docs"
      REDIS_URL: "redis://redis_cache:6379"
      STORAGE_URL: "http://minio:9000"
    command: sh -c "npx prisma migrate dev --name init_fresh && npx prisma db seed && npm run dev"
    depends_on:
      mysql:
        condition: service_healthy

  #database
  mysql:
    image: mysql:8.0.44-debian
    container_name: mysql_database
    restart: "always"
    environment:
      MYSQL_DATABASE: edu_connect
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # redis
  redis_cache:
    image: redis:bookworm
    container_name: redis_cache
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Minio storage
  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000" # Console & API
      - "9001:9001" # Web UI (optional, newer MinIO)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: "always"

volumes:
  mysql_data:
  redis_data:
  minio_data:
